# Site settings
title: Chris Matthias
email: chris.matthias@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I help graphic designers and ad agencies wrangle the web for their clients
  across all browsers and on new devices like mobile phones and tablets.
  Don't sweat the web&emdash; that's what friends are for.
url: "http://www.chrismatthias.com" # the base hostname & protocol for your site - used for feed.xml
twitter_username: thetrickster88
github_username:  thetrickster

# Build settings
markdown: kramdown

# Sass settings
# sass:
  # sass_dir: "assets/scss"


# Exclude files from jekyll build
exclude:
  - "assets/js/app.js"
  - "assets/scss/*.scss"
  - "assets/vendor/foundation-sites/"
  - "assets/vendor/jquery/"
  - "assets/vendor/motion-ui/"
  - "assets/vendor/what-input/"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "LICENSE.md"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "start.sh"
  - "stop.sh"

# Verification Codes
google-verification: k3_m0XO2nKKTOQ-RMLnQ5GfoTdOsUSz_7Wiz3BN42bs

# Site Branding
branding:
  theme_color_primary: "#0099CC"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
# incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5
